import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: { default: "Next", template: "%s | Codevolution", absolute: "" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body>
            <Navigation />
            {children}
            {/* <ErrorWrapper>{children}</ErrorWrapper> */}
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
